version: '3.8'
services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        # command: 'php artisan serve --host=0.0.0.0'
        # user: "ahmad-x:${GIP}"
        volumes:
            - .:/php
            #- ./sock:/var/run/dev-test/
            - /var/run/docker.sock:/var/run/dev-test
        ports:
            - 80:80
            